[permissions] Supplement broadcast permissions for UDisksListen. OMP#OS-5687
sailfishos/sailjail-permissions pull request #118
Opened 2022-01-28 15:39 UTC by DieTime

For the correct synchronization of the partition model, it is necessary to enable the UDisks2 service to listen to the signals of  `org.freedesktop.DBus.ObjectManager.*` and `org.freedesktop.DBus.Properties.*` interfaces.

Without them, the status of the partition is synchronized incorrectly (mounted or unmounted, etc.).

2022-01-31 12:42 UTC, aroditelev approved these changes

2022-02-01 06:08 UTC, spiiroin requested changes
Rationale and changes make sense to me.

However, the explanation is only in PR discussion part - which is not readily available when browsing git history later on -> I'd suggest adding it also to commit message.

2022-02-01 15:04 UTC, DieTime commented
Added a description to the commit message

2022-02-03 13:04 UTC, dseight approved these changes

2022-02-04 06:05 UTC, spiiroin approved these changes

2022-02-04 06:53 UTC, rainemak approved these changes

2022-02-04 06:54 UTC, merged